view: test {
    label: "test"
    sql_table_name: "Sales Insights - Databricks_demo"."test";;
    dimension: d_Custom_Day_Of_Month {
        label: "Custom Day Of Month"
        group_label: "Date Attributes"
        type: string
        sql: ${TABLE}."d_Custom_Day_Of_Month";;
    }

    dimension: d_Custom_Day_Of_Week {
        label: "Custom Day Of Week"
        group_label: "Date Attributes"
        type: string
        sql: ${TABLE}."d_Custom_Day_Of_Week";;
    }

    dimension: d_Custom_Day_Of_Year {
        label: "Custom Day Of Year"
        group_label: "Date Attributes"
        type: string
        sql: ${TABLE}."d_Custom_Day_Of_Year";;
    }

    dimension: d_Custom_Month_Name {
        label: "Custom Month Name"
        group_label: "Date Attributes"
        type: string
        sql: ${TABLE}."d_Custom_Month_Name";;
    }

    dimension: d_Custom_Month_Of_Quarter {
        label: "Custom Month Of Quarter"
        group_label: "Date Attributes"
        type: string
        sql: ${TABLE}."d_Custom_Month_Of_Quarter";;
    }

    dimension: d_Custom_Month_Of_Year {
        label: "Custom Month Of Year"
        group_label: "Date Attributes"
        type: string
        sql: ${TABLE}."d_Custom_Month_Of_Year";;
    }

    dimension: d_Custom_Quarter_Of_Year {
        label: "Custom Quarter Of Year"
        group_label: "Date Attributes"
        type: string
        sql: ${TABLE}."d_Custom_Quarter_Of_Year";;
    }

    dimension: d_Custom_Week_Of_Month {
        label: "Custom Week Of Month"
        group_label: "Date Attributes"
        type: string
        sql: ${TABLE}."d_Custom_Week_Of_Month";;
    }

    dimension: d_Custom_Week_Of_Year {
        label: "Custom Week Of Year"
        group_label: "Date Attributes"
        type: string
        sql: ${TABLE}."d_Custom_Week_Of_Year";;
    }

    dimension: CustomPP445_customday {
        label: " Custom Day"
        description: "A 445 calendar with custom parallel period keys defined for each level.  The underlying data matches the results of the Retail445 hierarchy because the data table contains the standard key assignments generated by the default ParallelPeriod logic.  A real custom ParallelPeriod hierarchy would have different parallel period key assignments to satisfy the rpt business's rpt comparison requirements."
        group_label: "Date Attributes.CustomPP445"
        type: date
        sql: ${TABLE}."customday";;
    }

    dimension: CustomPP445_custommonth {
        label: "   Custom Month"
        description: "Same as [Retail445].[rpt Month] but has a custom parallel period key."
        group_label: "Date Attributes.CustomPP445"
        type: string
        sql: ${TABLE}."custommonth";;
        drill_fields: [CustomPP445_customweek]
    }

    dimension: CustomPP445_customquarter {
        label: "    Custom Quarter"
        description: "Same as [Retail445].[rpt Quarter] but has a custom parallel period key."
        group_label: "Date Attributes.CustomPP445"
        type: string
        sql: ${TABLE}."customquarter";;
        drill_fields: [CustomPP445_custommonth]
    }

    dimension: CustomPP445_customweek {
        label: "  Custom Week"
        description: "Same as [Retail445].[rpt Week] but has a custom parallel period key."
        group_label: "Date Attributes.CustomPP445"
        type: string
        sql: ${TABLE}."customweek";;
        drill_fields: [CustomPP445_customday]
    }

    dimension: CustomPP445_customyear {
        label: "     Custom Year"
        description: "Same as [Retail445].[rpt Year] but has a custom parallel period key."
        group_label: "Date Attributes.CustomPP445"
        type: string
        sql: ${TABLE}."customyear";;
        drill_fields: [CustomPP445_customquarter]
    }


    measure: m_factinternetsalesorig_orderquantity_sum {
        label: "Order Quantity"
        type: sum
        sql: ${TABLE}."m_factinternetsalesorig_orderquantity_sum";;
    }

}
