
#
# This LookML file was generated by AtScale on 2024-09-03T13:21:33.267472929Z
#
# AtScale version: C2024.8.0
# Catalog: Sales Insights - gbq_main

connection: "atscale_veolia"
label: "Sales Insights - gbq_main"


include: "/views/Sales_Insights_-_gbq__main/Internet_Sales.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

