
#
# This LookML file was generated by AtScale on 2024-09-02T09:28:20.980509216Z
#
# AtScale version: C2024.8.0
# Catalog: Sales Insights - Databricks_demo

connection: "atscale_veolia"
label: "Sales Insights - Databricks_demo"


include: "/views/Sales_Insights_-_Databricks__demo/Internet_Sales.view.lkml"

include: "/views/Sales_Insights_-_Databricks__demo/test.view.lkml"


explore: Internet_Sales {
  label: "Internet Sales"
}

explore: test {
  label: "test"
}

