
#
# This LookML file was generated by AtScale on 2024-09-03T09:52:19.513555215Z
#
# AtScale version: C2024.8.0
# Catalog: TPCDS-MM-Snowflake_main

connection: "atscale_veolia"
label: "TPCDS-MM-Snowflake_main"


include: "/views/TPCDS-MM-Snowflake__main/DemoModel.view.lkml"


explore: DemoModel {
  label: "DemoModel"
}

